### ISSUE TITLE
v1.1.1: Adapter crash: "command.unshift is not a function"

### ISSUE THREAD

**Issue by ghost** [iobroker-community-adapters/ioBroker.hue#45]
Since the last several days, the adapter is regularly crashing with the error message "command.unshift is not a function" please see here: https://forum.iobroker.net/viewtopic.php?f=8&t=13979#p175104

The error occurs if -- for example -- I change a state of a device on in the adapter's object tree (e.g. from false to true). The device then sometimes turns on, or may not, but the adapter will crash almost for sure.
Deleting states or re-install, etc. did not help. My workaround was now to remove the adapter and to replace it with Node RED flows.

I was using adapter version 1.1.1.

Thanks. I really appreciate all your work on this, but finally needed a workaround now, as my Hue environment did no longer work and got many complaints, sitting in darkness, etc.

**Comment by Apollon77** [comment]
Posting the complete error here too may make things faster to get a fix

**Comment by ghost** [comment]
I agree, sorry for not sharing the log info, so here we go:

This first one is from the above mentioned thread, and I got all times the same errors:

`hue.0	2018-09-05 20:42:08.918	info	terminating
hue.0	2018-09-05 20:42:08.399	error	at Timer.listOnTimeout (timers.js:214:5)
hue.0	2018-09-05 20:42:08.399	error	at tryOnTimeout (timers.js:250:5)
hue.0	2018-09-05 20:42:08.399	error	at ontimeout (timers.js:386:11)
hue.0	2018-09-05 20:42:08.399	error	at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
hue.0	2018-09-05 20:42:08.399	error	TypeError: command.unshift is not a function
hue.0	2018-09-05 20:42:08.387	error	uncaught exception: command.unshift is not a function`

This second one also occurred once in a while:

`2018-09-15 21:55:40.934 - error: hue.0 uncaught exception: Cannot read property 'unshift' of undefined
2018-09-15 21:55:40.935 - error: hue.0 TypeError: Cannot read property 'unshift' of undefined
at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
2018-09-15 21:55:41.444 - info: hue.0 terminating
2018-09-15 21:55:41.472 - error: Caught by controller[0]: TypeError: Cannot read property 'unshift' of undefined
2018-09-15 21:55:41.472 - error: Caught by controller[0]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
2018-09-15 21:55:41.473 - error: Caught by controller[0]: at ontimeout (timers.js:498:11)
2018-09-15 21:55:41.473 - error: Caught by controller[0]: at tryOnTimeout (timers.js:323:5)
2018-09-15 21:55:41.473 - error: Caught by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
2018-09-15 21:55:41.473 - error: host.raspberrypi instance system.adapter.hue.0 terminated with code 0 (OK)
2018-09-15 21:55:41.473 - info: host.raspberrypi Restart adapter system.adapter.hue.0 because enabled`

**Comment by grimneko** [comment]
Same for me trying to control the "on" state or the level state of a Hue White from VIS.

Keeps crashing the HUE adapter with log saying:
`

Caught | 2018-10-21 04:43:13.460 | error | by controller[0]:     at Timer.listOnTimeout (timers.js:290:5)
-- | -- | -- | --
Caught | 2018-10-21 04:43:13.460 | error | by controller[0]:     at tryOnTimeout (timers.js:323:5)
Caught | 2018-10-21 04:43:13.460 | error | by controller[0]:     at ontimeout (timers.js:498:11)
Caught | 2018-10-21 04:43:13.460 | error | by controller[0]:     at Timeout.processCommands [as _onTimeout]  (/usr/local/www/iobroker/node_modules/iobroker.hue/main.js:546:21)
Caught | 2018-10-21 04:43:13.459 | error | by controller[0]: TypeError: command.unshift is not a function
hue.0 | 2018-10-21 04:43:13.452 | info | terminating
hue.0 | 2018-10-21 04:43:12.937 | error | at Timer.listOnTimeout (timers.js:290:5)
hue.0 | 2018-10-21 04:43:12.937 | error | at tryOnTimeout (timers.js:323:5)
hue.0 | 2018-10-21 04:43:12.937 | error | at ontimeout (timers.js:498:11)
hue.0 | 2018-10-21 04:43:12.937 | error | at Timeout.processCommands [as _onTimeout] (/usr/local/www/iobroker/node_modules/iobroker.hue/main.js:546:21)
hue.0 | 2018-10-21 04:43:12.937 | error | TypeError: command.unshift is not a function
hue.0 | 2018-10-21 04:43:12.937 | error | uncaught exception: command.unshift is not a function

`

Using adapter version 1.1.1.

**Comment by thommycgn** [comment]
For me the same... and the instances of every device are rebooting continuously. 

host.iobroker-pi | 2018-10-25 15:24:16.771 | error | instance system.adapter.hue.1 terminated with code 0 (OK)
-- | -- | -- | --
host.iobroker-pi | 2018-10-25 15:24:16.771 | error | Caught by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
host.iobroker-pi | 2018-10-25 15:24:16.770 | error | Caught by controller[0]: at tryOnTimeout (timers.js:323:5)
host.iobroker-pi | 2018-10-25 15:24:16.770 | error | Caught by controller[0]: at ontimeout (timers.js:498:11)
host.iobroker-pi | 2018-10-25 15:24:16.769 | error | Caught by controller[0]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
host.iobroker-pi | 2018-10-25 15:24:16.768 | error | Caught by controller[0]: TypeError: command.unshift is not a function
hue.1 | 2018-10-25 15:24:16.229 | error | TypeError: command.unshift is not a function at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21) at ontimeout (timers.js:498:11) at tryOnTim
hue.1 | 2018-10-25 15:24:16.228 | error | uncaught exception: command.unshift is not a function
hue.1 | 2018-10-25 15:24:16.151 | error | Timeout for polling light Philips_hue.Küche_Arbeitslicht




```
host.iobroker-pi | 2018-10-25 15:21:34.998 | error | instance system.adapter.hue.3 terminated with code 0 (OK)
-- | -- | -- | --
host.iobroker-pi | 2018-10-25 15:21:34.998 | error | Caught by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
host.iobroker-pi | 2018-10-25 15:21:34.998 | error | Caught by controller[0]: at tryOnTimeout (timers.js:323:5)
host.iobroker-pi | 2018-10-25 15:21:34.998 | error | Caught by controller[0]: at ontimeout (timers.js:498:11)
host.iobroker-pi | 2018-10-25 15:21:34.997 | error | Caught by controller[0]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
host.iobroker-pi | 2018-10-25 15:21:34.997 | error | Caught by controller[0]: TypeError: Cannot read property 'unshift' of undefined
hue.3 | 2018-10-25 15:21:34.459 | error | TypeError: Cannot read property 'unshift' of undefined at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21) at ontimeout (timers.js:498:11) a
hue.3 | 2018-10-25 15:21:34.459 | error | uncaught exception: Cannot read property 'unshift' of undefined
hue.4 | 2018-10-25 15:21:34.005 | error | Timeout for polling group 0
```


- and -


```
host.iobroker-pi | 2018-10-25 15:24:16.771 | error | instance system.adapter.hue.1 terminated with code 0 (OK)
-- | -- | -- | --
host.iobroker-pi | 2018-10-25 15:24:16.771 | error | Caught by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
host.iobroker-pi | 2018-10-25 15:24:16.770 | error | Caught by controller[0]: at tryOnTimeout (timers.js:323:5)
host.iobroker-pi | 2018-10-25 15:24:16.770 | error | Caught by controller[0]: at ontimeout (timers.js:498:11)
host.iobroker-pi | 2018-10-25 15:24:16.769 | error | Caught by controller[0]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
host.iobroker-pi | 2018-10-25 15:24:16.768 | error | Caught by controller[0]: TypeError: command.unshift is not a function
hue.1 | 2018-10-25 15:24:16.229 | error | TypeError: command.unshift is not a function at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21) at ontimeout (timers.js:498:11) at tryOnTim
hue.1 | 2018-10-25 15:24:16.228 | error | uncaught exception: command.unshift is not a function
hue.1 | 2018-10-25 15:24:16.151 | error | Timeout for polling light Philips_hue.Küche_Arbeitslicht


```

**Comment by algermi** [comment]
Servus zusammen, das gleiche auch bei mir. Möchte per YAHKA Osram Lightify Lampen steuern.





2018-11-14 18:52:01.581 - error: Caught by controller[0]: TypeError: command.unshift is not a function
--
2018-11-14 18:52:01.582 - error: Caught by controller[0]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
2018-11-14 18:52:01.582 - error: Caught by controller[0]: at ontimeout (timers.js:386:11)
2018-11-14 18:52:01.582 - error: Caught by controller[0]: at tryOnTimeout (timers.js:250:5)
2018-11-14 18:52:01.583 - error: Caught by controller[0]: at Timer.listOnTimeout (timers.js:214:5)
2018-11-14 18:52:01.583 - error: Caught by controller[1]: TypeError: Cannot read property 'unshift' of undefined
2018-11-14 18:52:01.583 - error: Caught by controller[1]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:20)
2018-11-14 18:52:01.583 - error: Caught by controller[1]: at ontimeout (timers.js:386:11)
2018-11-14 18:52:01.583 - error: Caught by controller[1]: at tryOnTimeout (timers.js:250:5)
2018-11-14 18:52:01.583 - error: Caught by controller[1]: at Timer.listOnTimeout (timers.js:214:5)
2018-11-14 18:52:01.584 - error: host.ioBroker instance system.adapter.hue.0 terminated with code 0 (OK)
2018-11-14 18:52:01.584 - info: host.ioBroker Restart adapter system.adapter.hue.0 because enabled
2018-11-14 18:52:31.625 - info: host.ioBroker instance system.adapter.hue.0 started with pid 7715
2018-11-14 18:52:33.360 - info: hue.0 States connected to redis: 127.0.0.1:6379
2018-11-14 18:52:33.540 - info: hue.0 starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.hue, node: v6.11.4
2018-11-14 18:52:33.666 - info: hue.0 creating/updating switch channels
2018-11-14 18:52:33.668 - info: hue.0 created/updated 1 switch channels
2018-11-14 18:52:33.677 - info: hue.0 created/updated 11 light channels
2018-11-14 18:52:33.678 - info: hue.0 creating/updating light groups
2018-11-14 18:52:33.685 - info: hue.0 created/updated 5 light groups
2018-11-14 18:52:33.685 - info: hue.0 creating/updating bridge device
2018-11-14 18:56:59.154 - error: hue.0 uncaught exception: Cannot read property 'unshift' of undefined
2018-11-14 18:56:59.155 - error: hue.0 TypeError: Cannot read property 'unshift' of undefined
at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:20)
at ontimeout (timers.js:386:11)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
2018-11-14 18:56:59.661 - info: hue.0 terminating
2018-11-14 18:56:59.699 - error: Caught by controller[0]: TypeError: Cannot read property 'unshift' of undefined
2018-11-14 18:56:59.707 - error: Caught by controller[0]: at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:20)
2018-11-14 18:56:59.708 - error: Caught by controller[0]: at ontimeout (timers.js:386:11)
2018-11-14 18:56:59.708 - error: Caught by controller[0]: at tryOnTimeout (timers.js:250:5)
2018-11-14 18:56:59.709 - error: Caught by controller[0]: at Timer.listOnTimeout (timers.js:214:5)
2018-11-14 18:56:59.709 - error: host.ioBroker instance system.adapter.hue.0 terminated with code 0 (OK)
2018-11-14 18:56:59.709 - info: host.ioBroker Restart adapter system.adapter.hue.0 because enabled
2018-11-14 18:57:29.785 - info: host.ioBroker instance system.adapter.hue.0 started with pid 7985
2018-11-14 18:57:31.525 - info: hue.0 States connected to redis: 127.0.0.1:6379
2018-11-14 18:57:31.713 - info: hue.0 starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.hue, node: v6.11.4
2018-11-14 18:57:31.842 - info: hue.0 creating/updating switch channels
2018-11-14 18:57:31.844 - info: hue.0 created/updated 1 switch channels
2018-11-14 18:57:31.853 - info: hue.0 created/updated 11 light channels
2018-11-14 18:57:31.853 - info: hue.0 creating/updating light groups
2018-11-14 18:57:31.860 - info: hue.0 created/updated 5 light groups
2018-11-14 18:57:31.861 - info: hue.0 creating/updating bridge device

**Comment by Zefau** [comment]
Same error for me

```
host.ioBroker-RasPi | 2018-12-03 19:16:36.541 | error | instance system.adapter.hue.0 terminated with code 0 (OK)
host.ioBroker-RasPi | 2018-12-03 19:16:36.540 | error | Caught by controller[0]:     at Timer.listOnTimeout (timers.js:290:5)
host.ioBroker-RasPi | 2018-12-03 19:16:36.539 | error | Caught by controller[0]:     at tryOnTimeout (timers.js:323:5)
host.ioBroker-RasPi | 2018-12-03 19:16:36.538 | error | Caught by controller[0]:     at ontimeout (timers.js:498:11)
host.ioBroker-RasPi | 2018-12-03 19:16:36.536 | error | Caught by controller[0]:     at Timeout.processCommands [as _onTimeout] (/opt/iobroker/node_modules/iobroker.hue/main.js:546:21)
host.ioBroker-RasPi | 2018-12-03 19:16:36.535 | error | Caught by controller[0]: TypeError: Cannot read property 'unshift' of undefined
```

**Comment by GermanBluefox** [comment]
Must be fixed by https://github.com/ioBroker/ioBroker.hue/commit/a60d425e2879540370d3b096ee05a818ba6a1a18
