### ISSUE TITLE
Colormode (xy); level.color.xy nachdem ansteuern der Datenpunkte Fehler im Log

### ISSUE THREAD

**Issue by FLAI16** [iobroker-community-adapters/ioBroker.hue#58]
Hallo,

ich bekomme diese Error-Mitteilungen im Log sobald ich die Datenpunkte hue.0.XXXXX.XXXXX.xy versuche zu steuern.

2019-02-11 21:43:38.974 - error: Caught by controller[0]: TypeError: Cannot read property 'x' of undefined
--
2019-02-11 21:43:38.975 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.hue/hue.js:193:33)
2019-02-11 21:43:38.975 - error: Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
2019-02-11 21:43:38.975 - error: Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
2019-02-11 21:43:38.975 - error: Caught by controller[0]: at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-02-11 21:43:38.975 - error: Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
2019-02-11 21:43:38.976 - error: Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
2019-02-11 21:43:38.976 - error: Caught by controller[0]: at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-02-11 21:43:38.976 - error: Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
2019-02-11 21:43:38.976 - error: Caught by controller[0]: at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-parser/index.js:251:12)
2019-02-11 21:43:38.976 - error: Caught by controller[0]: at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:335:16)
2019-02-11 21:43:38.976 - error: host.raspberrypi instance system.adapter.hue.0 terminated with code 0 (OK)

Ist das Problem schon bekannt???

**Comment by foxriver76** [comment]
Die Frage ist, wie du den Datenpunkt beschreibst. Hier fehlen leider Informationen.

**Comment by foxriver76** [comment]
Kann es nicht nachstellen: z. B. `0.1453,0.3557` in den Datenpunkt zu setzen funktioniert problemlos und wird ausgeführt.
