### ISSUE TITLE
Datenpunkt "on" einer Gruppe

### ISSUE THREAD

**Issue by Spampunk** [iobroker-community-adapters/ioBroker.hue#69]
Der Datenpunkt "on" zeigt nur dann "true" an, wenn alle Lampen innerhalb der Gruppe eingeschaltet sind. Es sollte die Möglichkeit geben, dass nicht nur "all_on" angezeigt wird, sondern auch "any_on". Dies müsste dann natürlich auch schaltbar sein.

**Comment by foxriver76** [comment]
Die Frage ist, wie möchtest du `any_on` schaltbar haben. Die einzige logische Richtung wäre, `any_on` auszuschalten, allerdings könnte man dann auch gleich den normalen `on` DP der Gruppe nutzen.

**Comment by Spampunk** [comment]
Es gibt zwei Gründe:
1. Darstellung im VIS. Ist ein Licht einer Gruppe an, wird mir das in der Gruppen-Übersicht signalisiert. Im Moment müssen halt **alle** Leuchten an sein, damit die Gruppe auch mit "an" dargestellt wird.
2. Vereinfachung der Schalter-Programmierung. (wenn Gruppe = an, dann Gruppe = aus und visversa).

Die Logik any_on ist auch der Standard in der offiziellen Hue- sowie weitere Apps, die ich bisher verwendet habe.

Natürlich könnte ich mir weitere Datenpunkte mit any_on erzeugen. Das wäre aber nicht so übersichtlich und mit mehr Programmieraufwand versehen. Auch die Wartung (Gruppen kommen hinzu oder werden gelöscht) wird damit komplizierter.

**Comment by foxriver76** [comment]
Ich verstehe schon den Sinn der Anzeige, allerdings erwartest du dann schon, dass setzen des any_on DPs die Gruppe komplett anmacht. Die Logik vom Namen ist ja nur, dass gerade irgendwas in der Gruppe an ist (deshalb interpretiere ich ihn eher als non-writeable). Allerdings klar für die Schalterlogik, wäre es schick, wenn dieser steuerbar ist.

**Comment by Spampunk** [comment]
Any_on könnte read only sein, da es nur um den Status geht.

**Comment by foxriver76** [comment]
Werde das mal noch einbauen bevor das ganze zum offiziellen Test angeboten wird.

**Comment by foxriver76** [comment]
Leider wird es für die 'all' Gruppe nicht möglich sein. Im config Objekt wird der 'any_on' status mitgeliefert, jedoch 'Gruppe 0' nicht. config.groups sieht z. B. so aus:
```json
{"1":{"name":"Wohnzimmer ohne Decke","lights":["2","13"],"sensors":[],"type":"Room","state":{"all_on":false,"any_on":false},"recycle":false,"class":"Living room","action":{"on":false,"bri":254,"hue":39787,"sat":0,"effect":"none","xy":[0.435,0.405],"ct":154,"alert":"select","colormode":"hs"}},"2":{"name":"Küche Indirekte Beleuchtung","lights":["4","5"],"sensors":[],"type":"Room","state":{"all_on":false,"any_on":false},"recycle":false,"class":"Kitchen","action":{"on":false,"bri":254,"ct":366,"alert":"none","colormode":"ct"}},"3":{"name":"WZ Indirekte Beleuchtung","lights":["6","7","8","9","10","11","17","18"],"sensors":[],"type":"Room","state":{"all_on":false,"any_on":false},"recycle":false,"class":"Living room","action":{"on":false,"bri":254,"alert":"none"}},"5":{"name":"SchlafDecke","lights":["21"],"sensors":[],"type":"Room","state":{"all_on":false,"any_on":false},"recycle":false,"class":"Other","action":{"on":false,"bri":254,"ct":156,"alert":"select","colormode":"ct"}},"7":{"name":"Wandbeleuchtung","lights":["12"],"sensors":[],"type":"Room","state":{"all_on":false,"any_on":false},"recycle":false,"class":"Other","action":{"on":false,"bri":254,"hue":51773,"sat":254,"effect":"none","xy":[0.2896,0.1136],"ct":153,"alert":"none","colormode":"hs"}}}
```

Die Gruppe 0 wird separat gepollt. Hier wird jedoch nur folgendes JSON geliefert:
```json
{"id":"0","name":"Group 0","type":"LightGroup","lights":["2","4","5","6","7","8","9","10","11","12","13","17","18","19","20","21"],"lastAction":{"on":false,"bri":254,"hue":39787,"sat":0,"effect":"none","xy":[0.435,0.405],"ct":156,"alert":"select","colormode":"ct"}}
```

**Comment by Spampunk** [comment]
Für die Gruppe 'all' ist das auch nicht notwendig, meiner Meinung nach. Kommt ja eher selten vor, dass man tatsächlich alle Lampen auf einmal anmachen möchte. Es geht ja eher um Räume (mir zumindest), die mehrere Lampen haben und bei denen auch einmal vereinzelt Lampen an sein können.

Wäre es denn möglich, den state 'any_on' auszulesen und per read only als DP darzustellen?

**Comment by foxriver76** [comment]
Sollte schon so sein, musst nur nochmal neu von GitHub laden + Upload

**Comment by Spampunk** [comment]
jau, super! Hab 1.000 Dank! 👍

**Comment by Spampunk** [comment]
sorry, muss noch mal nerven. Jetzt bekomme ich Fehler, hier mein Log:


2019-09-23 21:09:35.080 - info: host.IOTA Restart adapter system.adapter.hue.0 because enabled
--
2019-09-23 21:09:39.077 - warn: paw.0 problem with request: connect ECONNREFUSED 192.168.37.49:8080
2019-09-23 21:09:39.077 - warn: paw.0 ignorelist:192.168.37.49
2019-09-23 21:09:44.016 - info: web.0 <==Disconnect system.user.admin from ::ffff:192.168.37.49 vis.0
2019-09-23 21:09:47.640 - info: web.0 ==>Connected system.user.admin from ::ffff:192.168.37.49
2019-09-23 21:10:05.728 - info: host.IOTA instance system.adapter.hue.0 started with pid 11216
2019-09-23 21:10:07.932 - info: hue.0 starting. Version 2.0.0 in D:/iobroker/node_modules/iobroker.hue, node: v12.1.0
2019-09-23 21:10:08.140 - info: hue.0 skip switch: Daylight.configured
2019-09-23 21:10:08.142 - info: hue.0 skip switch: Daylight.sunriseoffset
2019-09-23 21:10:08.142 - info: hue.0 skip switch: Daylight.sunsetoffset
2019-09-23 21:10:08.143 - info: hue.0 created/updated 3 sensor channels
2019-09-23 21:10:08.150 - info: hue.0 created/updated 33 light channels
2019-09-23 21:10:08.155 - warn: hue.0 channel "Garten" already exists, using "Garten_Room" for group 12
2019-09-23 21:10:08.156 - warn: hue.0 channel "Kemenate" already exists, using "Kemenate_Room" for group 15
2019-09-23 21:10:08.157 - info: hue.0 created/updated 17 groups channels
2019-09-23 21:10:08.160 - info: hue.0 created/updated 79 scenes
2019-09-23 21:10:08.160 - info: hue.0 creating/updating bridge device
2019-09-23 21:10:12.563 - error: hue.0 uncaught exception: Cannot read property 'ack' of null
2019-09-23 21:10:12.563 - error: hue.0 TypeError: Cannot read property 'ack' of null
at handleParam (D:\iobroker\node_modules\iobroker.hue\main.js:90:55)
at D:\iobroker\node_modules\iobroker.hue\main.js:156:17
at D:\iobroker\node_modules\iobroker.js-controller\lib\adapter.js:4613:61
at Socket. (D:\iobroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:157:27)
at Socket.onack (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
at Socket.onpacket (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
at Manager. (D:\iobroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
at Manager.Emitter.emit (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
at Manager.ondecoded (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
at Decoder. (D:\iobroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-09-23 21:10:12.564 - info: hue.0 cleaned everything up...
2019-09-23 21:10:13.577 - info: hue.0 cleaned everything up...
2019-09-23 21:10:13.798 - error: Caught by controller[0]: TypeError: Cannot read property 'ack' of null
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at handleParam (D:\iobroker\node_modules\iobroker.hue\main.js:90:55)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at D:\iobroker\node_modules\iobroker.hue\main.js:156:17
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at D:\iobroker\node_modules\iobroker.js-controller\lib\adapter.js:4613:61
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Socket. (D:\iobroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:157:27)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Socket.onack (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Socket.onpacket (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Manager. (D:\iobroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Manager.Emitter.emit (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Manager.ondecoded (D:\iobroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
2019-09-23 21:10:13.800 - error: Caught by controller[0]: at Decoder. (D:\iobroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-09-23 21:10:13.801 - error: host.IOTA instance system.adapter.hue.0 terminated with code 6 (uncaught exception)
2019-09-23 21:10:13.801 - info: host.IOTA Restart adapter system.adapter.hue.0 because enabled

**Comment by Spampunk** [comment]
Hab den Server mal neu gebootet, jetzt scheint's wieder zu laufen. Keine Ahnung, woran es lag.

**Comment by foxriver76** [comment]
Hm, gibt es den Raum `Garten` und `Kemenate` tatsächlich zwei mal bei dir, bzw. Raum und Leuchtmittel z. B.? Falls es nochmal vorkommt (was durchaus wahrscheinlich ist), bitte Bescheid geben.

**Comment by Spampunk** [comment]
Ich habe Licht und Raum den gleichen Namen gegeben. Vielleicht nicht die beste Idee.

Im Moment läuft aber alles ok.

**Comment by foxriver76** [comment]
Okay, ne dann passt das ja was er da am Anfang loggt zumindest. Ist ja durchaus legitim das zu tun.
